{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "85ca8284-9e20-4d95-836d-c723a0e7a2ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q.1 what is an exception in python ? write the difference between exception and syntax error.\n",
    "\n",
    "\n",
    "ans.\n",
    "\n",
    "\n",
    "In Python, an exception is an event that occurs during the execution of a program and disrupts\n",
    "the normal flow of the program. When an exceptional situation occurs, Python raises an exception,\n",
    "which is a special type of object that represents the error condition. If not properly handled, \n",
    "an exception can cause the program to terminate abruptly.\n",
    "\n",
    "Exceptions can be raised in various situations, such as division by zero, accessing an index \n",
    "that is out of range, or attempting to open a non-existent file, among others.\n",
    "Python provides a mechanism to catch and handle exceptions through the \n",
    "use of `try`, `except`, `else`, and `finally` blocks, allowing the program to gracefully \n",
    "handle error scenarios.\n",
    "\n",
    "Difference between exception and syntax error:\n",
    "\n",
    "1. **Exception:**\n",
    "   - An exception is a runtime error that occurs during the execution of a Python program.\n",
    "   - Exceptions are raised when the interpreter detects an error in the program's logic or \n",
    "     when an unexpected situation arises during runtime.\n",
    "   - Examples of exceptions include `ZeroDivisionError`, `IndexError`, `FileNotFoundError`, etc.\n",
    "\n",
    "2. **Syntax Error:**\n",
    "   - A syntax error is a type of error that occurs during the parsing phase before the program is executed.\n",
    "   - Syntax errors are raised when the Python interpreter encounters invalid Python syntax in the code.\n",
    "   - Examples of syntax errors include misspelled keywords, missing colons, unmatched parentheses, etc.\n",
    "\n",
    "In summary, the key difference between an exception and a syntax error is when they occur and what causes them:\n",
    "\n",
    "- Exceptions occur during the runtime execution of the program when something unexpected or \n",
    "  erroneous happens (e.g., dividing by zero, accessing an invalid index).\n",
    "- Syntax errors occur during the parsing phase, before the program starts running,\n",
    "  due to incorrect Python syntax in the code (e.g., misspelled keywords, missing colons). \n",
    " They prevent the program from running at all until the syntax errors are fixed.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3844225e-cd16-40b1-b787-654c2b6c24a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. What happens when an exception is not handled? Explain with an example.\n",
    "\n",
    "ans.\n",
    "\n",
    "When an exception is not handled in a Python program, it causes the program to terminate abruptly,\n",
    "and an error message (traceback) is displayed, indicating the cause of the exception. \n",
    "This behavior is known as an \"unhandled exception.\"\n",
    "\n",
    "When an exception occurs during the execution of a\n",
    "Python program and is not caught and handled using `try` and `except` blocks, \n",
    "the exception propagates up the call stack until it reaches the top level of the program.\n",
    "At this point, Python displays an error message with the traceback information, \n",
    "indicating the type of exception, the line number where the exception occurred,\n",
    "and the sequence of function calls that led to the exception.\n",
    "\n",
    "* anexample to demonstrate what happens when an exception is not handled:\n",
    "\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    result = a / b\n",
    "    return result\n",
    "\n",
    "def main():\n",
    "    num1 = 10\n",
    "    num2 = 0\n",
    "    result = divide_numbers(num1, num2)\n",
    "    print(f\"Result: {result}\")\n",
    "\n",
    "main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9d31546-f8d7-49e2-8b7a-bd9cbf2aacca",
   "metadata": {},
   "outputs": [],
   "source": [
    "3. Which Python statements are used to catch and handle exceptions? Explain with an example\n",
    "\n",
    "ans.\n",
    "\n",
    "In Python, the try, except, else, and finally statements are used to catch and handle exceptions.\n",
    "These statements together form the try-except block, which allows you to handle exceptions gracefully\n",
    "and control the program's behavior when an exception occurs.\n",
    "\n",
    "The try block contains the code that may raise an exception. If an exception occurs in the try block, \n",
    "Python looks for a corresponding except block that matches the type of the exception raised. \n",
    "If a matching except block is found, the code inside the except block is executed, and\n",
    "the program continues its execution without terminating.\n",
    "\n",
    "You can have multiple except blocks to handle different types of exceptions. Additionally,\n",
    "you can use an optional else block, which will be executed if no exception occurs. \n",
    "The finally block,if provided, will be executed regardless of whether an exception occurred or not.\n",
    "\n",
    "Let's see an example to demonstrate how to catch and handle exceptions using the try-except block:\n",
    "\n",
    "\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        return result\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Cannot divide by zero!\")\n",
    "        return None\n",
    "\n",
    "def main():\n",
    "    num1 = 10\n",
    "    num2 = 0\n",
    "\n",
    "    try:\n",
    "        result = divide_numbers(num1, num2)\n",
    "        if result is not None:\n",
    "            print(f\"Result: {result}\")\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred: {e}\")\n",
    "\n",
    "main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6cd6416e-c24c-48e4-8dae-b137ff0ebfc3",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Explain with  an examples:\n",
    " a. try and else\n",
    " b. finally\n",
    " c. raise\n",
    "\n",
    "ans.\n",
    "\n",
    "a. try and else:\n",
    "The else block is used in conjunction with the try-except block to specify a block of code\n",
    "that should be executed only if no exceptions occur in the try block. \n",
    "If any exceptions are raised, the else block is skipped.\n",
    "\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Cannot divide by zero!\")\n",
    "    else:\n",
    "        print(f\"Result: {result}\")\n",
    "\n",
    "# Example 1: Division with valid inputs\n",
    "divide_numbers(10, 2)  # Output: Result: 5.0\n",
    "\n",
    "# Example 2: Division by zero\n",
    "divide_numbers(10, 0)  # Output: Error: Cannot divide by zero!\n",
    "\n",
    "\n",
    "\n",
    "b. finally:\n",
    "The finally block is used in a try-except block to specify a block of code that will always be executed, \n",
    "regardless of whether an exception occurred or not. \n",
    "The finally block is useful for cleanup actions, such as closing files or releasing resources\n",
    "\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Cannot divide by zero!\")\n",
    "    else:\n",
    "        print(f\"Result: {result}\")\n",
    "    finally:\n",
    "        print(\"Division operation completed.\")\n",
    "\n",
    "# Example 1: Division with valid inputs\n",
    "divide_numbers(10, 2)\n",
    "# Output:\n",
    "# Result: 5.0\n",
    "# Division operation completed.\n",
    "\n",
    "# Example 2: Division by zero\n",
    "divide_numbers(10, 0)\n",
    "# Output:\n",
    "# Error: Cannot divide by zero!\n",
    "# Division operation completed.\n",
    "\n",
    "\n",
    "c. raise:\n",
    "The raise statement is used to explicitly raise an exception in Python.\n",
    "It allows you to create and raise custom exceptions when certain conditions are met.\n",
    "\n",
    "def validate_age(age):\n",
    "    if age < 0:\n",
    "        raise ValueError(\"Age cannot be negative.\")\n",
    "    elif age < 18:\n",
    "        raise ValueError(\"You must be at least 18 years old.\")\n",
    "    else:\n",
    "        print(\"Age is valid.\")\n",
    "\n",
    "# Example 1: Valid age\n",
    "try:\n",
    "    validate_age(25)\n",
    "except ValueError as ve:\n",
    "    print(ve)\n",
    "# Output: Age is valid.\n",
    "\n",
    "# Example 2: Age is negative\n",
    "try:\n",
    "    validate_age(-5)\n",
    "except ValueError as ve:\n",
    "    print(ve)\n",
    "# Output: Age cannot be negative.\n",
    "\n",
    "# Example 3: Age is less than 18\n",
    "try:\n",
    "    validate_age(15)\n",
    "except ValueError as ve:\n",
    "    print(ve)\n",
    "# Output: You must be at least 18 years old.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "201026ec-ab54-4bcc-9346-c284d940eaa5",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an example.\n",
    "\n",
    "ans.\n",
    "\n",
    "\n",
    "Custom exceptions in Python are user-defined exceptions that extend the functionality of built-in exceptions.\n",
    "By creating custom exceptions, you can define your own error types and provide more meaningful and \n",
    "specific error messages to handle exceptional situations in your code.\n",
    "Custom exceptions help make your code more organized, easier to understand,\n",
    "and improve error handling by giving developers and users more insights into \n",
    "what went wrong in the program.\n",
    "\n",
    "We need custom exceptions in Python for the following reasons:\n",
    "\n",
    "1. **Better Error Messages:**\n",
    "       Custom exceptions allow you to provide descriptive error messages that are specific to your\n",
    "    application. This helps users and developers quickly identify the cause of the error and take \n",
    "    appropriate actions to resolve the issue.\n",
    "\n",
    "2. **Modularity and Reusability:**\n",
    "      Custom exceptions promote modularity in your code by encapsulating error conditions related \n",
    "    to a specific component or module. They can be reused across different parts of your program, \n",
    "    making the error handling consistent and easier to maintain.\n",
    "\n",
    "3. **Clearer Code Flow:**\n",
    "    By using custom exceptions, you can separate the error-handling logic from the main code flow.\n",
    "    This improves the readability of your code and allows you to focus on the main functionality\n",
    "    of your application without cluttering it with complex error handling.\n",
    "\n",
    "  *create a custom exception class named InvalidInputError to illustrate its usage:\n",
    "    \n",
    "\n",
    "class InvalidInputError(Exception):\n",
    "    \"\"\"Custom exception for invalid inputs.\"\"\"\n",
    "\n",
    "    def __init__(self, message):\n",
    "        super().__init__(message)\n",
    "        self.message = message\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    if b == 0:\n",
    "        raise InvalidInputError(\"Division by zero is not allowed.\")\n",
    "    return a / b\n",
    "\n",
    "try:\n",
    "    num1 = 10\n",
    "    num2 = 0\n",
    "    result = divide_numbers(num1, num2)\n",
    "except InvalidInputError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "else:\n",
    "    print(f\"Result: {result}\")\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
